version: "3.9"

services:
  db:
    image: supabase/postgres:15.1.0.88
    container_name: supabase-db
    restart: always
    volumes:
      - shared-data:/shared
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - odin-net

  studio:
    image: supabase/studio:latest
    container_name: supabase-studio
    restart: always
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://db:5432
      SUPABASE_URL: http://localhost:8000
      SUPABASE_ANON_KEY: "dev-anon-key"
      SUPABASE_SERVICE_ROLE_KEY: "dev-service-role-key"
    depends_on:
      - db
    networks:
      - odin-net
    volumes:
      - shared-data:/shared

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - ./n8n/docker.env
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: db
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: postgres
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: postgres
    networks:
      - odin-net
    volumes:
      - shared-data:/shared

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - odin-net
    volumes:
      - shared-data:/shared

  nginx:
    image: nginx:latest
    container_name: odin-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - odin-net

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: none
      device: /opt/odin-shared
      o: bind

networks:
  odin-net:
    driver: bridge
